List<integer> tempList = new list<integer>{5,21,15,99,77,101}; //this will add all these elements by default in the LIST.
integer sum1 = ListDemo2.add(tempList);
system.debug('sum1 is ' + sum1);


list <string> ls = new list <string> {'list', 'set', 'map','array'};
ls.add('methods');
ls.add('constructor');
listdemo2.iteratelistString(ls);
list <string> ls1 = new list <string>{'one', 'two', 'three','four'};
system.debug(listdemo2.add1(ls1));
ListDemo2.iterateListString99();
